aws:
    cognito:
        region: ${AWS_REGION}
        user-pool-id: ${AWS_COGNITO_USER_POOL_ID}
        client-id: ${AWS_COGNITO_CLIENT_ID}
        client-secret: ${AWS_COGNITO_CLIENT_SECRET}
        domain: ${AWS_COGNITO_DOMAIN}
        token-uri: ${AWS_COGNITO_DOMAIN}/oauth2/token
        redirect-uri: ${AWS_COGNITO_REDIRECT_URI}
show:
    error: ${SHOW_ERROR:never}
stripe:
    api-key: ${STRIPE_API_KEY}
    success-url: ${STRIPE_SUCCESS_URL}
    cancel-url: ${STRIPE_CANCEL_URL}

server:
    port: ${SERVER_PORT:8080}
    error:
        include-stacktrace: ${show.error:never}
        include-message: ${show.error:never}
        include-binding-errors: ${show.error:never}
spring:
    application:
        name: api
    datasource:
        url: jdbc:${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 60000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    liquibase:
        enabled: true
        url: jdbc:${DB_URL}
        user: ${DB_USER}
        password: ${DB_PASSWORD}
        change-log: classpath:db/changelog/db.changelog-master.json
        default-schema: smart_cart
        drop-first: false
        clear-checksums: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.user-pool-id}
                    jwk-set-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.user-pool-id}/.well-known/jwks.json
springdoc:
    swagger-ui:
        oauth:
            realm: Cognito
            app-name: Authorize API with AWS Cognitio
