server:
    port: ${SERVER_PORT:8080}
spring:
    application:
        name: api
    datasource:
        url: jdbc:postgresql://localhost:5432/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.json
        default-schema: smart_cart
        drop-first: false
        clear-checksums: false
