server:
    port: ${SERVER_PORT:8080}
stripe:
    api-key: ${STRIPE_API_KEY}
spring:
    application:
        name: api
    datasource:
        url: jdbc:${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 60000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    liquibase:
        enabled: true
        url: jdbc:${DB_URL}
        user: ${DB_USER}
        password: ${DB_PASSWORD}
        change-log: classpath:db/changelog/db.changelog-master.json
        default-schema: smart_cart
        drop-first: false
        clear-checksums: false
