[build]
  base = "webapp"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "22.13.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200